# Generated by Django 5.1.7 on 2025-04-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='mobile', max_length=50)),
                ('customer_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
