# Generated by Django 5.1.7 on 2025-04-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
