# Generated by Django 5.1.7 on 2025-04-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='category',
            field=models.CharField(choices=[('mobiles', 'Mobile'), ('laptops', 'Laptop'), ('clothes', 'Clothes'), ('books', 'Book')], max_length=10),
        ),
    ]
